title: Privacy Blog
author: Sheel Pant
email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  Sheel Pant Period 5
remote_theme: pages-themes/cayman@v0.2.0
plugins:
# - jekyll-remote-theme
# social links
twitter_username: your-twitter-handle # DO NOT include the @ character, or else the build will fail!
github_username:  your-github-handle # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
